FROM maven:3.8.3-openjdk-17 AS build
COPY ./ ./rso/app
WORKDIR ./rso/app
RUN mvn --show-version --update-snapshots --batch-mode clean package

FROM eclipse-temurin:17-jre
RUN mkdir ./rso/app
WORKDIR ./rso/app
COPY --from=build ./app/api/target/image-catalog-api-1.0.0-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java", "-jar", "image-catalog-api-1.0.0-SNAPSHOT.jar"]
