kumuluzee:
  name: katalog-destinacij-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/KatalogDestinacijDS
      connection-url: jdbc:postgresql://cornelius.db.elephantsql.com:5432/nwwikuzy
      username: nwwikuzy
      password: Lzyr5Nsj5W1emnEDiX8Yy_BApgExJSka
  # elephantsql dovoljuje samo 5 povezav na bazo, healthchecki jih ustvarijo več
  #health:
  #  checks:
  #    data-source-health-check:
  #      type: liveness
  #      jndi-name: jdbc/KatalogDestinacijDS
  metrics:
    web-instrumentation:
      - name: destinacije-endpoint
        url-pattern: /v1/katalogDestinacij/*
rest-properties:
  broken: false

