kumuluzee:
  name: katalog-destinacij-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/KatalogDestinacijDS
      connection-url: jdbc:postgresql://ep-ancient-fog-19741782-pooler.eu-central-1.aws.neon.tech/izletnik
      username: grzin
      password: ep2sMLqtu3rk
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/KatalogDestinacijDS
  metrics:
    web-instrumentation:
      - name: destinacije-endpoint
        url-pattern: /v1/katalogDestinacij/*
rest-properties:
  broken: false

