kumuluzee:
  name: katalog-destinacij-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/KatalogDestinacijDS
      connection-url: jdbc:postgresql://ep-twilight-meadow-75165427.eu-central-1.aws.neon.tech/katalog-destinacij-db
      username: urbi.cor
      password: XW6sdZnq3jpH
    #  connection-url: jdbc:postgresql://localhost:5432/katalog-destinacij
    #  username: dbuser
    #  password: postgres
    - jndi-name: jdbc/NeonTechKatalogDestinacijDS
      connection-url: jdbc:postgresql://ep-twilight-meadow-75165427.eu-central-1.aws.neon.tech/katalog-destinacij-db
      username: urbi.cor
      password: XW6sdZnq3jpH
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/NeonTechKatalogDestinacijDS
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                              <Configuration name="comments">
                                  <Appenders>
                                      <Console name="console" target="SYSTEM_OUT">
                                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                      </Console>
                                      <Socket name="logstash" host="f4e5773d-c9f5-4519-9c8d-495ce795f5be-ls.logit.io"
                                      port="22241" protocol="udp">
                                          <JSONLayout complete="false " compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                      </Socket>
                                  </Appenders>
                                  <Loggers>
                                      <!-- Default logger -->
                                      <Root level="all">
                                          <AppenderRef ref="console" level="info" />
                                          <AppenderRef ref="logstash" level="trace" />
                                      </Root>
                                  </Loggers>
                              </Configuration>'
  metrics:
    web-instrumentation:
      - name: destinacije-endpoint
        url-pattern: /v1/katalogDestinacij/*
  openapi-mp:
    enabled: true
    servlet:
      mapping: /v1/katalogDestinacij/openapi
    scan:
      packages:
        - si.fri.rso.katalog-destinacij.api
    ui:
      mapping: /v1/uporabnik/api-specs/ui
      specification-server: http://localhost:8080
  cors:
    enabled: true
    paths: "/*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    expose-headers: "Location,Content-Disposition"
    max-age: 3600
    credentials: false
    allowed-origin: "*"
rest-properties:
  broken: false

